export type Country = {
  name: string
  code: string   // ISO 3166-1 alpha-2
  dial: string   // e.g. "+60"
  states?: string[]
}

export const COUNTRIES: Country[] = [
  { name: 'Malaysia', code: 'MY', dial: '+60', states: ['Johor','Kedah','Kelantan','Kuala Lumpur','Labuan','Malacca','Negeri Sembilan','Pahang','Penang','Perak','Perlis','Putrajaya','Sabah','Sarawak','Selangor','Terengganu'] },
  { name: 'Singapore', code: 'SG', dial: '+65', states: ['Central Region','East Region','North Region','North-East Region','West Region'] },
  { name: 'Indonesia', code: 'ID', dial: '+62', states: ['Aceh','Bali','Banten','Bengkulu','Central Java','Central Kalimantan','Central Sulawesi','East Java','East Kalimantan','East Nusa Tenggara','Gorontalo','Jakarta','Jambi','Lampung','Maluku','North Kalimantan','North Maluku','North Sulawesi','North Sumatra','Papua','Riau','Riau Islands','South Kalimantan','South Sulawesi','South Sumatra','Southeast Sulawesi','Special Region of Yogyakarta','West Java','West Kalimantan','West Nusa Tenggara','West Papua','West Sulawesi','West Sumatra'] },
  { name: 'Philippines', code: 'PH', dial: '+63', states: ['Bicol','Cagayan Valley','Calabarzon','Caraga','Central Luzon','Central Visayas','Cordillera','Davao','Eastern Visayas','Ilocos','Metro Manila','Mimaropa','Mindanao','Northern Mindanao','Soccsksargen','Western Visayas','Zamboanga Peninsula'] },
  { name: 'Thailand', code: 'TH', dial: '+66', states: ['Bangkok','Chiang Mai','Chiang Rai','Chonburi','Khon Kaen','Nakhon Ratchasima','Nonthaburi','Pathum Thani','Phuket','Rayong','Songkhla','Udon Thani'] },
  { name: 'Vietnam', code: 'VN', dial: '+84', states: ['An Giang','Ba Ria-Vung Tau','Binh Dinh','Binh Duong','Binh Thuan','Ca Mau','Can Tho','Da Nang','Dong Nai','Hanoi','Ho Chi Minh City','Hue','Khanh Hoa','Long An','Quang Nam','Quang Ninh'] },
  { name: 'Australia', code: 'AU', dial: '+61', states: ['Australian Capital Territory','New South Wales','Northern Territory','Queensland','South Australia','Tasmania','Victoria','Western Australia'] },
  { name: 'New Zealand', code: 'NZ', dial: '+64', states: ['Auckland','Bay of Plenty','Canterbury','Gisborne','Hawke\'s Bay','Manawatu-Whanganui','Marlborough','Nelson','Northland','Otago','Southland','Taranaki','Tasman','Waikato','Wellington','West Coast'] },
  { name: 'United States', code: 'US', dial: '+1', states: ['Alabama','Alaska','Arizona','Arkansas','California','Colorado','Connecticut','Delaware','Florida','Georgia','Hawaii','Idaho','Illinois','Indiana','Iowa','Kansas','Kentucky','Louisiana','Maine','Maryland','Massachusetts','Michigan','Minnesota','Mississippi','Missouri','Montana','Nebraska','Nevada','New Hampshire','New Jersey','New Mexico','New York','North Carolina','North Dakota','Ohio','Oklahoma','Oregon','Pennsylvania','Rhode Island','South Carolina','South Dakota','Tennessee','Texas','Utah','Vermont','Virginia','Washington','West Virginia','Wisconsin','Wyoming'] },
  { name: 'Canada', code: 'CA', dial: '+1', states: ['Alberta','British Columbia','Manitoba','New Brunswick','Newfoundland and Labrador','Northwest Territories','Nova Scotia','Nunavut','Ontario','Prince Edward Island','Quebec','Saskatchewan','Yukon'] },
  { name: 'United Kingdom', code: 'GB', dial: '+44', states: ['England','Northern Ireland','Scotland','Wales'] },
  { name: 'India', code: 'IN', dial: '+91', states: ['Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Delhi','Goa','Gujarat','Haryana','Himachal Pradesh','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal'] },
  { name: 'China', code: 'CN', dial: '+86', states: ['Anhui','Beijing','Chongqing','Fujian','Gansu','Guangdong','Guangxi','Guizhou','Hainan','Hebei','Heilongjiang','Henan','Hong Kong','Hubei','Hunan','Inner Mongolia','Jiangsu','Jiangxi','Jilin','Liaoning','Macau','Ningxia','Qinghai','Shaanxi','Shandong','Shanghai','Shanxi','Sichuan','Tianjin','Tibet','Xinjiang','Yunnan','Zhejiang'] },
  { name: 'Japan', code: 'JP', dial: '+81', states: ['Aichi','Akita','Aomori','Chiba','Ehime','Fukui','Fukuoka','Fukushima','Gifu','Gunma','Hiroshima','Hokkaido','Hyogo','Ibaraki','Ishikawa','Iwate','Kagawa','Kagoshima','Kanagawa','Kochi','Kumamoto','Kyoto','Mie','Miyagi','Miyazaki','Nagano','Nagasaki','Nara','Niigata','Oita','Okayama','Okinawa','Osaka','Saga','Saitama','Shiga','Shimane','Shizuoka','Tochigi','Tokushima','Tokyo','Tottori','Toyama','Wakayama','Yamagata','Yamaguchi','Yamanashi'] },
  { name: 'South Korea', code: 'KR', dial: '+82', states: ['Busan','Chungcheongbuk-do','Chungcheongnam-do','Daegu','Daejeon','Gangwon-do','Gwangju','Gyeonggi-do','Gyeongsangbuk-do','Gyeongsangnam-do','Incheon','Jeju','Jeollabuk-do','Jeollanam-do','Seoul','Ulsan'] },
  { name: 'Germany', code: 'DE', dial: '+49', states: ['Baden-Württemberg','Bavaria','Berlin','Brandenburg','Bremen','Hamburg','Hesse','Lower Saxony','Mecklenburg-Vorpommern','North Rhine-Westphalia','Rhineland-Palatinate','Saarland','Saxony','Saxony-Anhalt','Schleswig-Holstein','Thuringia'] },
  { name: 'France', code: 'FR', dial: '+33' },
  { name: 'Netherlands', code: 'NL', dial: '+31' },
  { name: 'Switzerland', code: 'CH', dial: '+41' },
  { name: 'Sweden', code: 'SE', dial: '+46' },
  { name: 'Norway', code: 'NO', dial: '+47' },
  { name: 'Denmark', code: 'DK', dial: '+45' },
  { name: 'Finland', code: 'FI', dial: '+358' },
  { name: 'Spain', code: 'ES', dial: '+34' },
  { name: 'Italy', code: 'IT', dial: '+39' },
  { name: 'Portugal', code: 'PT', dial: '+351' },
  { name: 'Belgium', code: 'BE', dial: '+32' },
  { name: 'Austria', code: 'AT', dial: '+43' },
  { name: 'Poland', code: 'PL', dial: '+48' },
  { name: 'Czech Republic', code: 'CZ', dial: '+420' },
  { name: 'Hungary', code: 'HU', dial: '+36' },
  { name: 'Romania', code: 'RO', dial: '+40' },
  { name: 'Greece', code: 'GR', dial: '+30' },
  { name: 'Turkey', code: 'TR', dial: '+90' },
  { name: 'United Arab Emirates', code: 'AE', dial: '+971', states: ['Abu Dhabi','Ajman','Dubai','Fujairah','Ras al-Khaimah','Sharjah','Umm al-Quwain'] },
  { name: 'Saudi Arabia', code: 'SA', dial: '+966', states: ['Asir','Al Bahah','Al Jawf','Al Madinah','Al Qassim','Eastern Province','Hail','Jizan','Mecca','Najran','Northern Borders','Riyadh','Tabuk'] },
  { name: 'Qatar', code: 'QA', dial: '+974' },
  { name: 'Kuwait', code: 'KW', dial: '+965' },
  { name: 'Bahrain', code: 'BH', dial: '+973' },
  { name: 'Oman', code: 'OM', dial: '+968' },
  { name: 'Jordan', code: 'JO', dial: '+962' },
  { name: 'Lebanon', code: 'LB', dial: '+961' },
  { name: 'Egypt', code: 'EG', dial: '+20' },
  { name: 'South Africa', code: 'ZA', dial: '+27', states: ['Eastern Cape','Free State','Gauteng','KwaZulu-Natal','Limpopo','Mpumalanga','North West','Northern Cape','Western Cape'] },
  { name: 'Nigeria', code: 'NG', dial: '+234' },
  { name: 'Kenya', code: 'KE', dial: '+254' },
  { name: 'Ghana', code: 'GH', dial: '+233' },
  { name: 'Brazil', code: 'BR', dial: '+55' },
  { name: 'Mexico', code: 'MX', dial: '+52' },
  { name: 'Argentina', code: 'AR', dial: '+54' },
  { name: 'Colombia', code: 'CO', dial: '+57' },
  { name: 'Chile', code: 'CL', dial: '+56' },
  { name: 'Peru', code: 'PE', dial: '+51' },
  { name: 'Bangladesh', code: 'BD', dial: '+880' },
  { name: 'Pakistan', code: 'PK', dial: '+92' },
  { name: 'Sri Lanka', code: 'LK', dial: '+94' },
  { name: 'Nepal', code: 'NP', dial: '+977' },
  { name: 'Myanmar', code: 'MM', dial: '+95' },
  { name: 'Cambodia', code: 'KH', dial: '+855' },
  { name: 'Laos', code: 'LA', dial: '+856' },
  { name: 'Brunei', code: 'BN', dial: '+673' },
  { name: 'Taiwan', code: 'TW', dial: '+886' },
  { name: 'Hong Kong', code: 'HK', dial: '+852' },
  { name: 'Macau', code: 'MO', dial: '+853' },
  { name: 'Mongolia', code: 'MN', dial: '+976' },
  { name: 'Kazakhstan', code: 'KZ', dial: '+7' },
  { name: 'Uzbekistan', code: 'UZ', dial: '+998' },
  { name: 'Russia', code: 'RU', dial: '+7' },
  { name: 'Ukraine', code: 'UA', dial: '+380' },
  { name: 'Israel', code: 'IL', dial: '+972' },
  { name: 'Iran', code: 'IR', dial: '+98' },
  { name: 'Iraq', code: 'IQ', dial: '+964' },
  { name: 'Afghanistan', code: 'AF', dial: '+93' },
  { name: 'Ethiopia', code: 'ET', dial: '+251' },
  { name: 'Tanzania', code: 'TZ', dial: '+255' },
  { name: 'Uganda', code: 'UG', dial: '+256' },
  { name: 'Zimbabwe', code: 'ZW', dial: '+263' },
  { name: 'Mozambique', code: 'MZ', dial: '+258' },
  { name: 'Morocco', code: 'MA', dial: '+212' },
  { name: 'Algeria', code: 'DZ', dial: '+213' },
  { name: 'Tunisia', code: 'TN', dial: '+216' },
  { name: 'Libya', code: 'LY', dial: '+218' },
  { name: 'Sudan', code: 'SD', dial: '+249' },
  { name: 'Venezuela', code: 'VE', dial: '+58' },
  { name: 'Ecuador', code: 'EC', dial: '+593' },
  { name: 'Bolivia', code: 'BO', dial: '+591' },
  { name: 'Paraguay', code: 'PY', dial: '+595' },
  { name: 'Uruguay', code: 'UY', dial: '+598' },
  { name: 'Panama', code: 'PA', dial: '+507' },
  { name: 'Costa Rica', code: 'CR', dial: '+506' },
  { name: 'Cuba', code: 'CU', dial: '+53' },
  { name: 'Dominican Republic', code: 'DO', dial: '+1' },
  { name: 'Haiti', code: 'HT', dial: '+509' },
  { name: 'Jamaica', code: 'JM', dial: '+1' },
  { name: 'Guatemala', code: 'GT', dial: '+502' },
  { name: 'Honduras', code: 'HN', dial: '+504' },
  { name: 'El Salvador', code: 'SV', dial: '+503' },
  { name: 'Nicaragua', code: 'NI', dial: '+505' },
  { name: 'Iceland', code: 'IS', dial: '+354' },
  { name: 'Ireland', code: 'IE', dial: '+353' },
  { name: 'Luxembourg', code: 'LU', dial: '+352' },
  { name: 'Malta', code: 'MT', dial: '+356' },
  { name: 'Cyprus', code: 'CY', dial: '+357' },
  { name: 'Slovakia', code: 'SK', dial: '+421' },
  { name: 'Croatia', code: 'HR', dial: '+385' },
  { name: 'Slovenia', code: 'SI', dial: '+386' },
  { name: 'Serbia', code: 'RS', dial: '+381' },
  { name: 'Bulgaria', code: 'BG', dial: '+359' },
  { name: 'Albania', code: 'AL', dial: '+355' },
  { name: 'Bosnia and Herzegovina', code: 'BA', dial: '+387' },
  { name: 'North Macedonia', code: 'MK', dial: '+389' },
  { name: 'Montenegro', code: 'ME', dial: '+382' },
  { name: 'Kosovo', code: 'XK', dial: '+383' },
  { name: 'Moldova', code: 'MD', dial: '+373' },
  { name: 'Belarus', code: 'BY', dial: '+375' },
  { name: 'Lithuania', code: 'LT', dial: '+370' },
  { name: 'Latvia', code: 'LV', dial: '+371' },
  { name: 'Estonia', code: 'EE', dial: '+372' },
  { name: 'Georgia', code: 'GE', dial: '+995' },
  { name: 'Armenia', code: 'AM', dial: '+374' },
  { name: 'Azerbaijan', code: 'AZ', dial: '+994' },
]

// Sorted alphabetically with Malaysia first for local relevance
export const SORTED_COUNTRIES: Country[] = [
  COUNTRIES[0], // Malaysia first
  ...COUNTRIES.slice(1).sort((a, b) => a.name.localeCompare(b.name)),
]

export function getStatesForCountry(countryName: string): string[] {
  return COUNTRIES.find(c => c.name === countryName)?.states ?? []
}

export function getDialCode(countryName: string): string {
  return COUNTRIES.find(c => c.name === countryName)?.dial ?? ''
}

export const GENDER_OPTIONS = [
  'Male', 'Female', 'Non-binary', 'Prefer not to say', 'Other',
]

export const ETHNICITY_OPTIONS = [
  'Malay', 'Chinese', 'Indian', 'Kadazan', 'Iban', 'Bajau', 'Murut', 'Orang Asli',
  'Arab', 'Eurasian', 'Caucasian / White', 'Black / African', 'Hispanic / Latino',
  'Middle Eastern', 'South Asian', 'Southeast Asian', 'East Asian', 'Mixed / Biracial',
  'Prefer not to say', 'Other',
]
